version: "3"
services:
    mysqldb:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD : root  # Replace with your desired MySQL root password
          MYSQL_DATABASE: devops
          MYSQL_USER: mysql
          MYSQL_PASSWORD: root
        volumes:
         - ./data.sql:/docker-entrypoint-initdb.d/data.sql
        networks:
         - dev-net 
    backend:
        image: chikaftw/devopsregistry:latest
        container_name: spring
        ports:
            - "8082:8082"
        restart: unless-stopped
        depends_on:
            - mysqldb
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devops?allowPublicKeyRetrieval=true&useSSL=false
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        networks:
         - dev-net          
          
          
    frontend:
      image: chikaftw/devopsfront2:latest
      container_name: angular
      ports :
        - "4200:4200"
      restart: unless-stopped
      depends_on:
          - backend
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - "9090:9090"
      networks:
      - dev-net
    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        - prometheus
      networks:
      - dev-net

networks:
  dev-net:
volumes:
  db: {}
