version: "3"
services:
    mysqldb:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD : root  # Replace with your desired MySQL root password
          MYSQL_DATABASE: devops
          MYSQL_USER: mysql
          MYSQL_PASSWORD: root
    frontend:
      image: chikaftw/devopsfront2:latest
      container_name: angular
      ports :
        - 3000:3000
      restarts: unless-stopped
      depends_on:
        - spring
         
    backend:
        image: chikaftw/devopsregistry:latest
        container_name: spring
        ports:
            - "127.0.0.1:8082:8082"
        restart: unless-stopped
        depends_on:
            - mysqldb
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devops?allowPublicKeyRetrieval=true&useSSL=false
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

volumes:
  db: {}
